// TODO: global variables

podTemplate(
  inheritFrom: "jenkins-agent" ,
  containers: [
    containerTemplate(name: "java-container", image: "maven:3.8.6-openjdk-11-slim", alwaysPullImage: false, ttyEnabled: true, command: "cat"),
  ]
) {
  node(POD_LABEL) {
    stage("CodeCheckout_1") {
      checkout([$class: "GitSCM", userRemoteConfigs: [[url: "https://github.com/samar-belhadj/leto-nearcare.git", credentialsId: "github"]], branches: [[name: "main"]]])
    }
    stage("BuildAndTestJava_1") {
      container("java-container") {
        dir('config-server'){
        sh """
          mvn -f "./pom.xml" -s "./settings.xml" clean install
        """
        }
      }
    }
    stage("DockerBuild_1") {
      container("docker-daemon") {

        dir('config-server'){  
            sh """
              docker build -t "talenteoregistry.azurecr.io/config-server:1.0.0" -f "../gitops/docker/Dockerfile" "./"
            """

        }
          }
    }
    stage("DockerPush_1") {
      container("docker-daemon") {
          withDockerRegistry(credentialsId: 'talenteoregistry', url: 'https://talenteoregistry.azurecr.io') {
            sh """
              docker push "talenteoregistry.azurecr.io/config-server:1.0.0"
            """
          }
        
      }
    }
  }
}
